name: Deploy Docusaurus to EC2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Execute remote deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/projects/docs
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .
            git pull origin main
            rm -rf node_modules package-lock.json build/
            npm install
            npm run build